services:
  docs:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
      args:
        PYTHON_VERSION: 3.13
    image: retrogaming
    volumes:
      - .:/app:cached
    command: /start
    environment:
      - SPHINX_COMMAND=html
    ports:
      - "5000:5000"
  docs-test:
    image: retrogaming
    volumes:
      - .:/app:cached
    command: /start
    environment:
      - SPHINX_COMMAND=doctest -E
