#!/bin/sh

# Basically we watch only README.rst, LICENCE.rst and everything under django_structlog
sphinx-autobuild src /src/_build/html \
-b ${SPHINX_COMMAND} \
--port 5000 \
--host 0.0.0.0 \
--watch src
