name: gh-pages
on:
  push:
    branches:
      - main
jobs:
  deploy-gh-pages:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install ghp-import
      - name: make html
        working-directory: src
        run: make html
      - name: Deploy website
        run: |
          pip install ghp-import
          ghp-import -n -p -m "Build git hash $(git rev-parse --short HEAD)" -f src/_build/html
